apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: gpu-app-hpa
  namespace: namespace  #Mention namespace here
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gpu-app-deployment  # Change to your deployment name
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: your_metric  # Replace with your metric name
        target:
          type: AverageValue
          averageValue: 50
