apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-adapter-config
  namespace: monitoring #Namespace name here
data:
  config.yaml: |
    rules:
      custom:
        - seriesQuery: '{job="gpu-metrics-service"}'  # Query for your application metrics
          resources:
            template: <<.Resource>>
          metricsQuery: sum(rate(gpu_utilization[1m]))  # Define how to fetch GPU metrics
          name:
            matches: "^(.*)_total$"
            as: "${1}"
          labels:
            instance: ""
